# This is a basic workflow to help you get started with Actions

name: Publish CommerceClient.Api package to NuGet.org

# Controls when the action will run. Triggers the workflow on push request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    
    - name: Install dependencies
      working-directory: src
      run: dotnet restore
      
      #
    - name: Build
      working-directory: src
      run: dotnet build --configuration Release --no-restore
      
      #
    - name: Publish CommerceClient.Api to nuget.org
      working-directory: src/CommerceClient.Api.Online
      run: dotnet nuget push bin\Release\*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
      
#    - name: Publish CommerceClient.Api to github
#      working-directory: src/CommerceClient.Api.Online
#      run: dotnet nuget push bin\Release\*.nupkg -k ${{ secrets.GITHUB_TOKEN }}  -s "https://nuget.pkg.github.com/flemmingrothmann/index.json"  --skip-duplicate
    
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:        
        nuget-version: '5.x'

    - name: Nuget Add Source
      run: nuget sources Add -Name "github" -Source https://nuget.pkg.github.com/flemmingrothmann/index.json -UserName [flemmingrothmann] -Password ${{ secrets.GITHUB_TOKEN }}

    - name: Nuget SetAPIKey
      run: nuget setapikey ${{ secrets.GITHUB_TOKEN }} -Source "github"

    - name: Publish the package to GitHub packages
      working-directory: src/CommerceClient.Api.Online
      run: nuget push bin\Debug\*.nupkg -source "github" -SkipDuplicate